# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a50a263164350f426f927dfe7ad58330655589c5946de33a88bcc1330f2a86fb30a5c464bb7ffef14dd0edc3fb98a64681dabfa16ae0213f9e6836c39f128f0d

test:
  secret_key_base: d08b8af6cd827daf4f01c5aaee59d0c91aea94dd9282eb804bf7f6ef7b8131a4b4be06a79cc2aaa63b15666aa1cff18fe1dc22f5bbb02d261b2a57abd3bc1d7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
